theme = "blowfish"
hasCJKLanguage = true

# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

# baseURL = "https://changingmoments.vercel.app/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 72

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
