theme = "blowfish"
hasCJKLanguage = true

# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme = "blowfish"
# baseURL = "https://changingmoments.one/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 12
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

    ## Waline
    enableWaline = true
    walineServerURL = "https://comments-sikonn.vercel.app/"
    walineWordLimit = 0
    walineMeta = ["nick", "mail", "link"]
    walinePageSize = 10
    walineLang = "zh-CN"
    walineHighlight = true
    walineEmoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo", "https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili"]
    walineRequiredMeta = ["nick", "mail"]
    walineLogin = "enabled"
    walineCopyright = true
    # 说明：https://waline.js.org/