languageCode = "zh-CN"
languageName = "Chinese"
displayName = "ZH-CN"
isoCode = "zh-CN"
weight = 1
rtl = false

title = "蝴蝶曾在此处"
logo = "img/blowfish_logo_transparent.png"
description = "Another perfect day"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "暂时是一只河豚"
  image = "img/blowfish_logo.png"
  headline = "蝴蝶不知道被谁施了魔咒"
  bio = "但是真的是一只蝴蝶"
  links = [
    { email = "mailto:hello@your_domain.com" },
  ]
