# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Friends"
  url = "https://changingmoments.one/posts/friends/"
  weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "いただきます"
  url = "https://ramen-fsm.eu.org/tags/%E5%A4%A9%E5%A4%A9%E7%9B%BC%E7%9D%80%E5%90%83%E9%A5%AD"

[[footer]]
  name = "夢"
  url = "https://ramen-fsm.eu.org/tags/%E5%A4%A9%E5%A4%A9%E6%A2%A6%E6%B8%B8%E4%BB%99%E5%A2%83"

[[footer]]
  name = "嬉しい星"
  url = "https://ramen-fsm.eu.org/tags/%E5%9D%A0%E8%90%BD%E5%A4%A9%E8%BE%B9%E7%9A%84%E5%BF%AB%E4%B9%90%E7%A2%8E%E7%89%87"

[[footer]]
  name = "力"
  url = "https://ramen-fsm.eu.org/tags/%E5%A4%A9%E5%A4%A9%E5%85%85%E6%BB%A1%E5%8A%9B%E9%87%8F"

[[footer]]
  name = "本、ドラマ、映画"
  url = "https://ramen-fsm.eu.org/tags/%E5%A4%A9%E5%A4%A9%E4%B9%A6%E5%BD%B1%E9%81%A8%E6%B8%B8"

[[footer]]
  name = "Yakult—swallows"
  url = "https://ramen-fsm.eu.org/tags/%E3%83%A4%E3%82%AF%E3%83%AB%E3%83%88%E3%82%B9%E3%83%AF%E3%83%AD%E3%83%BC%E3%82%BA"

[[footer]]
  name = "推し"
  url = "https://ramen-fsm.eu.org/tags/%E6%8E%A8%E3%81%97%E3%81%97%E3%81%8B%E5%8B%9D%E3%81%9F%E3%82%93"

[[footer]]
  name = "猫"
  url = "https://ramen-fsm.eu.org/tags/%E8%99%8E%E7%9A%AE%E8%9B%8B%E7%B3%95%E5%91%BC%E5%99%9C%E5%8D%B7"
