[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

#[[main]]
#  name = "Months"
#  pageRef = "docs"
#  weight = 20

[[main]]
  name = "Archives"
  pageRef = "archive"
  weight = 20

[[main]]
  name = "About"
  weight = 30
[[main]]
  identifier = "goods"
  name = "friends"
  pageRef = "goods"
  parent = 'About'
  weight = 10