# Basic
title = "蝴蝶"
baseURL = "https://changingmoments.vercel.app/"
theme = "vno-hugo"

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 10
 [[menu.main]]
    name = "Tags"
    identifier = "Tags"
    url = "/tags/"
    weight = 20
[taxonomies]
    tag = "tags"
    
    
[params]
author = "蝴蝶"
subtitle = "就在此刻，改变时刻"
description = "日记，思考，感受."
welcomeMessage = "欢迎来到我的世界"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = ""

#[params.comment]
#disqus = "vno-hugo"
#duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
#weibo = "onevcat"
github = "sikonn"
#twitter = "onevcat"
#gplus = "107108267983477358170"
#mail = "onev@onevcat.com"

#[params.ga]
#ID = "your_ga_id"
#host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[permalinks]
posts = "/:year/:month/:title/"
