# Basic
title = "蝴蝶"
baseURL = "https://changingmoments.vercel.app/"
theme = "vno-hugo"
hasCJKLanguage = true 

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
 [[menu.main]]
    name = "Tags"
    identifier = "Tags"
    url = "/tags/"
    weight = 10
[taxonomies]
    tag = "tags"
 [[menu.main]]
    name = "Friends"
    identifier = "Friends"
    url = "https://changingmoments.vercel.app/2022/04/friends/"
    weight = 30
 [[menu.main]]
    name = "Albums"
    weight = 20
 [[menu.main]]
    name = "-飯"
    identifier = "Albums"
    parent = "Albums"
    url = "https://ramen-fsm.eu.org/tags/%E5%A4%A9%E5%A4%A9%E7%9B%BC%E7%9D%80%E5%90%83%E9%A5%AD"
    weight = 1
 [[menu.main]]
    name = "-夢"
    identifier = "Albums"
    parent = "Albums"
    url = "https://ramen-fsm.eu.org/tags/%E5%A4%A9%E5%A4%A9%E6%A2%A6%E6%B8%B8%E4%BB%99%E5%A2%83"
    weight = 2
 [[menu.main]]
    name = "-楽"
    identifier = "Albums"
    parent = "Albums"
    url = "https://ramen-fsm.eu.org/tags/%E5%9D%A0%E8%90%BD%E5%A4%A9%E8%BE%B9%E7%9A%84%E5%BF%AB%E4%B9%90%E7%A2%8E%E7%89%87"
    weight = 3
    
[params]
author = "蝴蝶"
subtitle = "就在此刻，改变时刻"
description = "日记，思考，感受，书影，野球."
welcomeMessage = "欢迎来到我的世界"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = ""

#[params.comment]
#disqus = "vno-hugo"
#duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
#weibo = "onevcat"
github = "sikonn"
#twitter = "onevcat"
#gplus = "107108267983477358170"
#mail = "onev@onevcat.com"

#[params.ga]
#ID = "your_ga_id"
#host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Posts"
description = "Visit blog"

[permalinks]
posts = "/:year/:month/:title/"
